"""Initial deployment migration

Revision ID: 9649b1297aa0
Revises: d385159aa7a8
Create Date: 2025-08-23 12:40:29.174253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9649b1297aa0'
down_revision = 'd385159aa7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('month', sa.VARCHAR(length=7), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
